2025-05-17 10:42:10,018 - INFO - Entered Main Function...
2025-05-17 10:42:11,223 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:42:11,223 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:42:11,226 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:42:11,226 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:42:15,442 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:42:15,506 - INFO - Filteration Ends
2025-05-17 10:42:15,510 - INFO - Reconciliation Ends
2025-05-17 10:42:15,610 - ERROR - Dummydata error: Object of type DataFrame is not JSON serializable
Traceback (most recent call last):
  File "d:\GitHub\RPA\src\app.py", line 187, in dummydata
    return handler(result,"")
  File "d:\GitHub\RPA\src\handler.py", line 13, in handler
    return jsonify({"isSuccess": has_data, "data": result})
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DataFrame is not JSON serializable

2025-05-17 10:42:18,739 - INFO - Entered Main Function...
2025-05-17 10:42:18,881 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:42:18,881 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:42:18,882 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:42:18,883 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:42:22,504 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:42:22,553 - INFO - Filteration Ends
2025-05-17 10:42:22,555 - INFO - Reconciliation Ends
2025-05-17 10:42:22,564 - ERROR - Dummydata error: Object of type DataFrame is not JSON serializable
Traceback (most recent call last):
  File "d:\GitHub\RPA\src\app.py", line 187, in dummydata
    return handler(result,"")
  File "d:\GitHub\RPA\src\handler.py", line 13, in handler
    return jsonify({"isSuccess": has_data, "data": result})
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DataFrame is not JSON serializable

2025-05-17 10:42:27,672 - INFO - Entered Main Function...
2025-05-17 10:42:27,826 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:42:27,826 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:42:27,828 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:42:27,828 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:42:31,106 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:42:31,177 - INFO - Filteration Ends
2025-05-17 10:42:31,181 - INFO - Reconciliation Ends
2025-05-17 10:42:31,205 - ERROR - Dummydata error: Object of type DataFrame is not JSON serializable
Traceback (most recent call last):
  File "d:\GitHub\RPA\src\app.py", line 187, in dummydata
    return handler(result,"")
  File "d:\GitHub\RPA\src\handler.py", line 13, in handler
    return jsonify({"isSuccess": has_data, "data": result})
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DataFrame is not JSON serializable

2025-05-17 10:45:20,615 - INFO - Entered Main Function...
2025-05-17 10:45:21,210 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:45:21,210 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:45:21,211 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:45:21,211 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:45:24,745 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:45:24,805 - INFO - Filteration Ends
2025-05-17 10:45:24,810 - INFO - Reconciliation Ends
2025-05-17 10:45:24,832 - ERROR - Dummydata error: Object of type DataFrame is not JSON serializable
Traceback (most recent call last):
  File "d:\GitHub\RPA\src\app.py", line 187, in dummydata
    return handler(result,"")
  File "d:\GitHub\RPA\src\handler.py", line 13, in handler
    return jsonify({"isSuccess": has_data, "data": result, "message": ""})
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DataFrame is not JSON serializable

2025-05-17 10:47:02,087 - INFO - Entered Main Function...
2025-05-17 10:47:03,178 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:47:03,178 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:47:03,179 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:47:03,179 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:47:06,546 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:47:06,660 - INFO - Filteration Ends
2025-05-17 10:47:06,670 - INFO - Reconciliation Ends
2025-05-17 10:47:06,711 - ERROR - Dummydata error: Object of type DataFrame is not JSON serializable
Traceback (most recent call last):
  File "d:\GitHub\RPA\src\app.py", line 187, in dummydata
    return handler(result,"")
  File "d:\GitHub\RPA\src\handler.py", line 13, in handler
    return jsonify({"isSuccess": has_data, "data": result, "message": " "})
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Sathyaswaruban\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\GitHub\RPA\.venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type DataFrame is not JSON serializable

2025-05-17 10:47:56,519 - INFO - Entered Main Function...
2025-05-17 10:47:57,303 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:47:57,303 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:47:57,304 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:47:57,304 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:48:00,583 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:48:00,636 - INFO - Filteration Ends
2025-05-17 10:48:00,640 - INFO - Reconciliation Ends
2025-05-17 10:48:24,001 - INFO - Entered Main Function...
2025-05-17 10:48:24,106 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:48:24,106 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:48:24,109 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:48:24,109 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:48:27,780 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:48:27,886 - INFO - Filteration Ends
2025-05-17 10:48:27,920 - INFO - Reconciliation Ends
2025-05-17 10:49:43,354 - INFO - Entered Main Function...
2025-05-17 10:49:43,439 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:49:43,439 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:49:43,440 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:49:43,440 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:49:43,441 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 10:49:43,441 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 10:49:47,584 - INFO - Entered Main Function...
2025-05-17 10:49:47,666 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:49:47,666 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:49:47,667 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:49:47,668 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:49:50,988 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:49:51,063 - INFO - Filteration Ends
2025-05-17 10:49:51,065 - INFO - Reconciliation Ends
2025-05-17 10:50:47,002 - INFO - Entered Main Function...
2025-05-17 10:50:47,099 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:50:47,100 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:50:47,101 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:50:47,101 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:50:47,103 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 10:50:47,103 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 10:50:49,215 - INFO - Entered Main Function...
2025-05-17 10:50:49,299 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:50:49,300 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:50:49,302 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:50:49,302 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:50:53,037 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:50:53,135 - INFO - Filteration Ends
2025-05-17 10:50:53,157 - INFO - Reconciliation Ends
2025-05-17 10:56:16,753 - INFO - Entered Main Function...
2025-05-17 10:56:17,230 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:56:17,230 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:56:17,231 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:56:17,231 - INFO - Fetching data from HUB for Recharge
2025-05-17 10:56:21,339 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 10:56:21,435 - INFO - Filteration Ends
2025-05-17 10:56:21,457 - INFO - Reconciliation Ends
2025-05-17 10:59:57,797 - INFO - Entered Main Function...
2025-05-17 10:59:58,517 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 10:59:58,517 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 10:59:58,518 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 10:59:58,519 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:00:02,629 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:00:02,737 - INFO - Filteration Ends
2025-05-17 11:00:02,764 - INFO - Reconciliation Ends
2025-05-17 11:00:50,249 - INFO - Entered Main Function...
2025-05-17 11:00:50,318 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:00:50,319 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:00:50,319 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:00:50,319 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:00:50,320 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:00:50,320 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:00:53,619 - INFO - Entered Main Function...
2025-05-17 11:00:53,679 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:00:53,679 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:00:53,680 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:00:53,681 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:00:56,802 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:00:56,875 - INFO - Filteration Ends
2025-05-17 11:00:56,879 - INFO - Reconciliation Ends
2025-05-17 11:02:17,764 - INFO - Entered Main Function...
2025-05-17 11:02:17,842 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:02:17,842 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:02:17,843 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:02:17,843 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:02:17,843 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:02:17,843 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:05:13,303 - INFO - Entered Main Function...
2025-05-17 11:05:13,384 - WARNING - No records found within the given date range!
2025-05-17 11:06:58,766 - INFO - Entered Main Function...
2025-05-17 11:06:58,844 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:06:58,845 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:06:58,846 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:06:58,846 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:07:02,063 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:07:02,193 - INFO - Filteration Ends
2025-05-17 11:07:02,197 - INFO - Reconciliation Ends
2025-05-17 11:07:14,565 - INFO - Entered Main Function...
2025-05-17 11:07:14,647 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:07:14,647 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:07:14,648 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:07:14,648 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:07:18,252 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:07:18,312 - INFO - Filteration Ends
2025-05-17 11:07:18,342 - INFO - Reconciliation Ends
2025-05-17 11:08:35,832 - INFO - Entered Main Function...
2025-05-17 11:08:35,911 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:08:35,911 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:08:35,912 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:08:35,912 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:08:35,913 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:08:35,914 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:12:30,447 - INFO - Entered Main Function...
2025-05-17 11:12:30,522 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:12:30,523 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:12:30,524 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:12:30,524 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:12:33,739 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:12:33,797 - INFO - Filteration Ends
2025-05-17 11:12:33,800 - INFO - Reconciliation Ends
2025-05-17 11:12:43,681 - INFO - Entered Main Function...
2025-05-17 11:12:43,726 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:12:43,726 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:12:43,727 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:12:43,727 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:12:47,256 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:12:47,338 - INFO - Filteration Ends
2025-05-17 11:12:47,362 - INFO - Reconciliation Ends
2025-05-17 11:13:17,471 - INFO - Entered Main Function...
2025-05-17 11:13:17,551 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:13:17,552 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:13:17,553 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:13:17,553 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:13:17,554 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:13:17,554 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:13:19,106 - INFO - Entered Main Function...
2025-05-17 11:13:19,172 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:13:19,173 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:13:19,173 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:13:19,173 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:13:22,354 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:13:22,457 - INFO - Filteration Ends
2025-05-17 11:13:22,460 - INFO - Reconciliation Ends
2025-05-17 11:14:29,272 - INFO - Entered Main Function...
2025-05-17 11:14:29,344 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:14:29,344 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:14:29,345 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:14:29,345 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:14:29,345 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:14:29,345 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:14:32,006 - INFO - Entered Main Function...
2025-05-17 11:14:32,128 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:14:32,128 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:14:32,129 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:14:32,130 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:14:35,907 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:14:36,074 - INFO - Filteration Ends
2025-05-17 11:14:36,097 - INFO - Reconciliation Ends
2025-05-17 11:16:27,314 - INFO - Entered Main Function...
2025-05-17 11:16:27,405 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:16:27,405 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:16:27,406 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:16:27,406 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:16:27,407 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:16:27,408 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:16:34,045 - INFO - Entered Main Function...
2025-05-17 11:16:34,162 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:16:34,163 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:16:34,164 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:16:34,164 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:16:37,866 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:16:37,956 - INFO - Filteration Ends
2025-05-17 11:16:37,971 - INFO - Reconciliation Ends
2025-05-17 11:17:13,895 - INFO - Entered Main Function...
2025-05-17 11:17:13,965 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:17:13,965 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:17:13,966 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:17:13,966 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:17:13,967 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:17:13,967 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:17:16,502 - INFO - Entered Main Function...
2025-05-17 11:17:16,591 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:17:16,591 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:17:16,593 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:17:16,593 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:17:20,347 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:17:20,408 - INFO - Filteration Ends
2025-05-17 11:17:20,430 - INFO - Reconciliation Ends
2025-05-17 11:18:19,402 - INFO - Entered Main Function...
2025-05-17 11:18:19,493 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:18:19,493 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:18:19,494 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:18:19,494 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:18:19,495 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:18:19,495 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:18:21,222 - INFO - Entered Main Function...
2025-05-17 11:18:21,307 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:18:21,308 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:18:21,310 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:18:21,310 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:18:25,085 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:18:25,185 - INFO - Filteration Ends
2025-05-17 11:18:25,211 - INFO - Reconciliation Ends
2025-05-17 11:20:25,286 - INFO - Entered Main Function...
2025-05-17 11:20:25,358 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:20:25,359 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:20:25,359 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:20:25,359 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:20:25,360 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:20:25,360 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:21:03,645 - INFO - Entered Main Function...
2025-05-17 11:21:03,780 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:21:03,780 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:21:03,785 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:21:03,785 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:21:07,490 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:21:07,583 - INFO - Filteration Ends
2025-05-17 11:21:07,605 - INFO - Reconciliation Ends
2025-05-17 11:21:37,459 - INFO - Entered Main Function...
2025-05-17 11:21:37,542 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:21:37,542 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:21:37,543 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:21:37,544 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:21:37,549 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:21:37,549 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:21:48,714 - INFO - Entered Main Function...
2025-05-17 11:21:48,777 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:21:48,777 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:21:48,778 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:21:48,787 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:21:52,031 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:21:52,126 - INFO - Filteration Ends
2025-05-17 11:21:52,128 - INFO - Reconciliation Ends
2025-05-17 11:23:10,268 - INFO - Entered Main Function...
2025-05-17 11:23:10,353 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:23:10,353 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:23:10,355 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:23:10,355 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:23:10,356 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:23:10,356 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:23:25,014 - INFO - Entered Main Function...
2025-05-17 11:23:25,079 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:23:25,079 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:23:25,080 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:23:25,080 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:23:28,700 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:23:28,816 - INFO - Filteration Ends
2025-05-17 11:23:28,857 - INFO - Reconciliation Ends
2025-05-17 11:24:17,838 - INFO - Entered Main Function...
2025-05-17 11:24:17,924 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:24:17,924 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:24:17,925 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:24:17,925 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:24:17,926 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:24:17,926 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:24:28,868 - INFO - Entered Main Function...
2025-05-17 11:24:28,921 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:24:28,921 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:24:28,922 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:24:28,922 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:24:32,495 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:24:32,566 - INFO - Filteration Ends
2025-05-17 11:24:32,595 - INFO - Reconciliation Ends
2025-05-17 11:26:35,792 - INFO - Entered Main Function...
2025-05-17 11:26:35,869 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:26:35,869 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:26:35,871 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:26:35,871 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:26:35,874 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:26:35,874 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:26:55,545 - INFO - Entered Main Function...
2025-05-17 11:26:55,602 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:26:55,603 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:26:55,604 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:26:55,605 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:26:58,726 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:26:58,792 - INFO - Filteration Ends
2025-05-17 11:26:58,796 - INFO - Reconciliation Ends
2025-05-17 11:27:18,312 - INFO - Entered Main Function...
2025-05-17 11:27:18,347 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:27:18,347 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:27:18,348 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:27:18,348 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:27:21,462 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:27:21,543 - INFO - Filteration Ends
2025-05-17 11:27:21,549 - INFO - Reconciliation Ends
2025-05-17 11:27:37,392 - INFO - Entered Main Function...
2025-05-17 11:27:37,434 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:27:37,434 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:27:37,435 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:27:37,435 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:27:41,369 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:27:41,457 - INFO - Filteration Ends
2025-05-17 11:27:41,478 - INFO - Reconciliation Ends
2025-05-17 11:28:11,529 - INFO - Entered Main Function...
2025-05-17 11:28:11,617 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:28:11,618 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:28:11,619 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:28:11,619 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:28:11,620 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:28:11,621 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:28:16,781 - INFO - Entered Main Function...
2025-05-17 11:28:16,847 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:28:16,847 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:28:16,848 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:28:16,848 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:28:21,260 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:28:21,349 - INFO - Filteration Ends
2025-05-17 11:28:21,370 - INFO - Reconciliation Ends
2025-05-17 11:28:31,621 - INFO - Entered Main Function...
2025-05-17 11:28:31,701 - WARNING - No records found within the given date range!
2025-05-17 11:28:50,135 - INFO - Entered Main Function...
2025-05-17 11:28:50,180 - WARNING - No records found within the given date range!
2025-05-17 11:29:23,471 - INFO - Entered Main Function...
2025-05-17 11:29:23,541 - WARNING - No records found within the given date range!
2025-05-17 11:37:24,484 - INFO - Entered Main Function...
2025-05-17 11:37:25,470 - WARNING - No records found within the given date range!
2025-05-17 11:37:25,474 - ERROR - Dummydata error: 'str' object has no attribute 'items'
Traceback (most recent call last):
  File "d:\GitHub\RPA\src\app.py", line 160, in dummydata
    for key, value in result.items():
                      ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'

2025-05-17 11:37:34,354 - INFO - Entered Main Function...
2025-05-17 11:37:34,407 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:37:34,407 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:37:34,408 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:37:34,408 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:37:38,230 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:37:38,320 - INFO - Filteration Ends
2025-05-17 11:37:38,350 - INFO - Reconciliation Ends
2025-05-17 11:40:55,125 - INFO - Entered Main Function...
2025-05-17 11:40:56,121 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:40:56,121 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:40:56,122 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:40:56,123 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:40:59,850 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:40:59,932 - INFO - Filteration Ends
2025-05-17 11:40:59,955 - INFO - Reconciliation Ends
2025-05-17 11:41:12,147 - INFO - Entered Main Function...
2025-05-17 11:41:12,201 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:41:12,201 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:41:12,202 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:41:12,202 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:41:15,534 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:41:15,582 - INFO - Filteration Ends
2025-05-17 11:41:15,584 - INFO - Reconciliation Ends
2025-05-17 11:41:49,946 - INFO - Entered Main Function...
2025-05-17 11:41:50,026 - WARNING - No records found within the given date range!
2025-05-17 11:42:15,206 - INFO - Entered Main Function...
2025-05-17 11:42:15,292 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:42:15,292 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:42:15,293 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:42:15,293 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:42:15,294 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 11:42:15,294 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 11:42:29,813 - INFO - Entered Main Function...
2025-05-17 11:42:29,894 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 11:42:29,894 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 11:42:29,895 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 11:42:29,895 - INFO - Fetching data from HUB for Recharge
2025-05-17 11:42:33,549 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 11:42:33,624 - INFO - Filteration Ends
2025-05-17 11:42:33,653 - INFO - Reconciliation Ends
2025-05-17 16:26:52,866 - INFO - Entered Main Function...
2025-05-17 16:26:53,634 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:26:53,634 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:26:53,636 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:26:53,636 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:26:58,018 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:26:58,164 - INFO - Filteration Ends
2025-05-17 16:26:58,200 - INFO - Reconciliation Ends
2025-05-17 16:29:39,105 - INFO - Entered Main Function...
2025-05-17 16:29:39,962 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:29:39,963 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:29:39,970 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:29:39,970 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:29:39,972 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 16:29:39,973 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 16:29:48,250 - INFO - Entered Main Function...
2025-05-17 16:29:50,072 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:29:50,072 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:29:50,085 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:29:50,085 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:29:53,920 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:29:53,994 - INFO - Filteration Ends
2025-05-17 16:29:53,997 - INFO - Reconciliation Ends
2025-05-17 16:30:13,656 - INFO - Entered Main Function...
2025-05-17 16:30:14,515 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:30:14,515 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:30:14,520 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:30:14,520 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:30:19,122 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:30:19,273 - INFO - Filteration Ends
2025-05-17 16:30:19,278 - INFO - Reconciliation Ends
2025-05-17 16:31:00,158 - INFO - Entered Main Function...
2025-05-17 16:31:00,870 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:31:00,870 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:31:00,875 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:31:00,875 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:31:00,876 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 16:31:00,876 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 16:31:08,494 - INFO - Entered Main Function...
2025-05-17 16:31:09,465 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:31:09,466 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:31:09,471 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:31:09,472 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:31:13,882 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:31:13,969 - INFO - Filteration Ends
2025-05-17 16:31:13,986 - INFO - Reconciliation Ends
2025-05-17 16:31:37,772 - INFO - Entered Main Function...
2025-05-17 16:31:38,425 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:31:38,425 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:31:38,430 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:31:38,431 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:31:44,390 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-17 16:31:44,391 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:31:44,528 - INFO - Filteration Ends
2025-05-17 16:31:44,550 - INFO - Reconciliation Ends
2025-05-17 16:33:50,286 - INFO - Entered Main Function...
2025-05-17 16:33:51,273 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:33:51,273 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:33:51,279 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:33:51,279 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:33:54,420 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:33:54,489 - INFO - Filteration Ends
2025-05-17 16:33:54,491 - INFO - Reconciliation Ends
2025-05-17 16:34:11,315 - INFO - Entered Main Function...
2025-05-17 16:34:11,793 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:34:11,793 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:34:11,796 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:34:11,796 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:34:15,428 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:34:15,512 - INFO - Filteration Ends
2025-05-17 16:34:15,514 - INFO - Reconciliation Ends
2025-05-17 16:38:01,929 - INFO - Entered Main Function...
2025-05-17 16:38:02,017 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:38:02,018 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:38:02,018 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:38:02,019 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:38:02,020 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 16:38:02,020 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 16:38:13,746 - INFO - Entered Main Function...
2025-05-17 16:38:13,825 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:38:13,825 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:38:13,826 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:38:13,826 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:38:17,796 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:38:17,895 - INFO - Filteration Ends
2025-05-17 16:38:17,914 - INFO - Reconciliation Ends
2025-05-17 16:38:47,369 - INFO - Entered Main Function...
2025-05-17 16:38:47,449 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:38:47,449 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:38:47,450 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:38:47,450 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:38:50,462 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-17 16:38:50,462 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:38:50,502 - INFO - Filteration Ends
2025-05-17 16:38:50,504 - INFO - Reconciliation Ends
2025-05-17 16:38:52,743 - INFO - Entered Main Function...
2025-05-17 16:38:52,801 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:38:52,801 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:38:52,802 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:38:52,802 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:38:56,047 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:38:56,135 - INFO - Filteration Ends
2025-05-17 16:38:56,138 - INFO - Reconciliation Ends
2025-05-17 16:39:13,930 - INFO - Entered Main Function...
2025-05-17 16:39:14,015 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:39:14,015 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:39:14,016 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:39:14,016 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:39:17,442 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:39:17,504 - INFO - Filteration Ends
2025-05-17 16:39:17,506 - INFO - Reconciliation Ends
2025-05-17 16:39:45,398 - INFO - Entered Main Function...
2025-05-17 16:39:45,461 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:39:45,461 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:39:45,462 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:39:45,462 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:39:49,871 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-17 16:39:49,872 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:39:49,960 - INFO - Filteration Ends
2025-05-17 16:39:49,982 - INFO - Reconciliation Ends
2025-05-17 16:44:39,699 - INFO - Entered Main Function...
2025-05-17 16:44:39,788 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:44:39,788 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:44:39,789 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:44:39,789 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:44:43,699 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:44:43,774 - INFO - Filteration Ends
2025-05-17 16:44:43,795 - INFO - Reconciliation Ends
2025-05-17 16:45:20,685 - INFO - Entered Main Function...
2025-05-17 16:45:20,774 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:45:20,774 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:45:20,775 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:45:20,775 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:45:20,776 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 16:45:20,776 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 16:50:49,122 - INFO - Entered Main Function...
2025-05-17 16:50:49,214 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:50:49,214 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:50:49,215 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:50:49,216 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:50:53,036 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:50:53,149 - INFO - Filteration Ends
2025-05-17 16:50:53,170 - INFO - Reconciliation Ends
2025-05-17 16:53:09,440 - INFO - Entered Main Function...
2025-05-17 16:53:09,529 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:53:09,529 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:53:09,530 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:53:09,530 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:53:09,531 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 16:53:09,532 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 16:53:21,135 - INFO - Entered Main Function...
2025-05-17 16:53:21,238 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:53:21,238 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:53:21,239 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:53:21,239 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:53:31,354 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.1.3' (timed out)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-17 16:53:31,354 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 16:53:44,972 - INFO - Entered Main Function...
2025-05-17 16:53:45,068 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:53:45,068 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:53:45,070 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:53:45,070 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:53:55,085 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.1.3' (timed out)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-17 16:53:55,086 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 16:53:59,748 - INFO - Entered Main Function...
2025-05-17 16:53:59,805 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:53:59,806 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:53:59,807 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:53:59,810 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:54:09,822 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.1.3' (timed out)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-17 16:54:09,822 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 16:54:15,872 - INFO - Entered Main Function...
2025-05-17 16:54:15,975 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 16:54:15,975 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 16:54:15,976 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 16:54:15,976 - INFO - Fetching data from HUB for Recharge
2025-05-17 16:54:19,215 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 16:54:19,271 - INFO - Filteration Ends
2025-05-17 16:54:19,273 - INFO - Reconciliation Ends
2025-05-17 16:59:59,719 - INFO - Entered Main Function...
2025-05-17 17:00:00,242 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:00:00,242 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:00:00,242 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:00:00,243 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:00:09,256 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:00:09,299 - INFO - Filteration Ends
2025-05-17 17:00:09,333 - INFO - Reconciliation Ends
2025-05-17 17:00:12,946 - INFO - Entered Main Function...
2025-05-17 17:00:13,075 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:00:13,075 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:00:13,076 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:00:13,076 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:00:19,206 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:00:19,325 - INFO - Filteration Ends
2025-05-17 17:00:19,354 - INFO - Reconciliation Ends
2025-05-17 17:03:09,529 - INFO - Entered Main Function...
2025-05-17 17:03:10,318 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:03:10,318 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:03:10,319 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:03:10,319 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:03:14,318 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:03:14,402 - INFO - Filteration Ends
2025-05-17 17:03:14,424 - INFO - Reconciliation Ends
2025-05-17 17:03:14,596 - ERROR - Dummydata error: name 'res' is not defined
Traceback (most recent call last):
  File "d:\GitHub\RPA\src\app.py", line 186, in dummydata
    print(result)
          ^^^
NameError: name 'res' is not defined

2025-05-17 17:03:34,682 - INFO - Entered Main Function...
2025-05-17 17:03:34,766 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:03:34,767 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:03:34,768 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:03:34,768 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:03:39,050 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:03:39,147 - INFO - Filteration Ends
2025-05-17 17:03:39,170 - INFO - Reconciliation Ends
2025-05-17 17:03:39,272 - ERROR - Dummydata error: name 'res' is not defined
Traceback (most recent call last):
  File "d:\GitHub\RPA\src\app.py", line 186, in dummydata
    print(result)
          ^^^
NameError: name 'res' is not defined

2025-05-17 17:04:30,977 - INFO - Entered Main Function...
2025-05-17 17:04:31,720 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:04:31,720 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:04:31,721 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:04:31,721 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:04:36,330 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:04:36,363 - INFO - Filteration Ends
2025-05-17 17:04:36,374 - INFO - Reconciliation Ends
2025-05-17 17:04:51,153 - INFO - Entered Main Function...
2025-05-17 17:04:51,244 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:04:51,244 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:04:51,245 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:04:51,245 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:04:54,359 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:04:54,428 - INFO - Filteration Ends
2025-05-17 17:04:54,430 - INFO - Reconciliation Ends
2025-05-17 17:06:21,966 - INFO - Entered Main Function...
2025-05-17 17:06:22,975 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:06:22,976 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:06:22,977 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:06:22,977 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:06:26,871 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:06:26,927 - INFO - Filteration Ends
2025-05-17 17:06:26,931 - INFO - Reconciliation Ends
2025-05-17 17:06:43,661 - INFO - Entered Main Function...
2025-05-17 17:06:43,740 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:06:43,740 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:06:43,741 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:06:43,741 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:06:47,584 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:06:47,651 - INFO - Filteration Ends
2025-05-17 17:06:47,674 - INFO - Reconciliation Ends
2025-05-17 17:10:33,554 - INFO - Entered Main Function...
2025-05-17 17:10:33,627 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:10:33,627 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:10:33,628 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:10:33,628 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:10:33,630 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:10:33,631 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:10:36,392 - INFO - Entered Main Function...
2025-05-17 17:10:36,444 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:10:36,444 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:10:36,445 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:10:36,445 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:10:40,365 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:10:40,437 - INFO - Filteration Ends
2025-05-17 17:10:40,461 - INFO - Reconciliation Ends
2025-05-17 17:11:07,554 - INFO - Entered Main Function...
2025-05-17 17:11:07,632 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:11:07,633 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:11:07,633 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:11:07,633 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:11:11,270 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-17 17:11:11,270 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:11:11,436 - INFO - Filteration Ends
2025-05-17 17:11:11,454 - INFO - Reconciliation Ends
2025-05-17 17:11:20,629 - INFO - Entered Main Function...
2025-05-17 17:11:20,722 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:11:20,722 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:11:20,724 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:11:20,724 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:11:24,255 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:11:24,315 - INFO - Filteration Ends
2025-05-17 17:11:24,317 - INFO - Reconciliation Ends
2025-05-17 17:20:11,770 - INFO - Entered Main Function...
2025-05-17 17:20:11,850 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:20:11,850 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:20:11,851 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:20:11,851 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:20:11,853 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:20:11,853 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:20:14,178 - INFO - Entered Main Function...
2025-05-17 17:20:14,255 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:20:14,255 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:20:14,256 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:20:14,257 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:20:17,669 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:20:17,740 - INFO - Filteration Ends
2025-05-17 17:20:17,743 - INFO - Reconciliation Ends
2025-05-17 17:20:31,036 - INFO - Entered Main Function...
2025-05-17 17:20:31,114 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:20:31,115 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:20:31,115 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:20:31,116 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:20:35,953 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:20:36,021 - INFO - Filteration Ends
2025-05-17 17:20:36,042 - INFO - Reconciliation Ends
2025-05-17 17:24:55,645 - INFO - Entered Main Function...
2025-05-17 17:24:56,472 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:24:56,472 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:24:56,474 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:24:56,474 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:25:00,488 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:25:00,619 - INFO - Filteration Ends
2025-05-17 17:25:00,650 - INFO - Reconciliation Ends
2025-05-17 17:26:09,075 - INFO - Entered Main Function...
2025-05-17 17:26:09,159 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:26:09,159 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:26:09,159 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:26:09,159 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:26:09,160 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:26:09,160 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:26:13,666 - INFO - Entered Main Function...
2025-05-17 17:26:13,728 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:26:13,728 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:26:13,728 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:26:13,728 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:26:18,110 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:26:18,191 - INFO - Filteration Ends
2025-05-17 17:26:18,212 - INFO - Reconciliation Ends
2025-05-17 17:27:14,638 - INFO - Entered Main Function...
2025-05-17 17:27:14,724 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:27:14,724 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:27:14,725 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:27:14,725 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:27:14,726 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:27:14,726 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:27:17,691 - INFO - Entered Main Function...
2025-05-17 17:27:17,754 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:27:17,754 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:27:17,755 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:27:17,755 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:27:21,501 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:27:21,592 - INFO - Filteration Ends
2025-05-17 17:27:21,614 - INFO - Reconciliation Ends
2025-05-17 17:27:35,252 - INFO - Entered Main Function...
2025-05-17 17:27:35,309 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:27:35,309 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:27:35,310 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:27:35,310 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:27:39,014 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:27:39,114 - INFO - Filteration Ends
2025-05-17 17:27:39,135 - INFO - Reconciliation Ends
2025-05-17 17:28:31,828 - INFO - Entered Main Function...
2025-05-17 17:28:31,909 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:28:31,909 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:28:31,910 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:28:31,910 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:28:31,911 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:28:31,911 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:28:39,906 - INFO - Entered Main Function...
2025-05-17 17:28:40,097 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:28:40,098 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:28:40,099 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:28:40,099 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:28:43,898 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:28:44,001 - INFO - Filteration Ends
2025-05-17 17:28:44,022 - INFO - Reconciliation Ends
2025-05-17 17:29:57,656 - INFO - Entered Main Function...
2025-05-17 17:29:57,766 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:29:57,766 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:29:57,767 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:29:57,767 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:29:57,767 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:29:57,767 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:30:08,038 - INFO - Entered Main Function...
2025-05-17 17:30:08,207 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:30:08,207 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:30:08,209 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:30:08,210 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:30:11,727 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:30:11,750 - INFO - Filteration Ends
2025-05-17 17:30:11,751 - INFO - Reconciliation Ends
2025-05-17 17:31:54,089 - INFO - Entered Main Function...
2025-05-17 17:31:54,172 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:31:54,172 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:31:54,173 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:31:54,173 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:31:54,174 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:31:54,175 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:32:20,257 - INFO - Entered Main Function...
2025-05-17 17:32:20,365 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:32:20,365 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:32:20,366 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:32:20,366 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:32:23,620 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:32:23,675 - INFO - Filteration Ends
2025-05-17 17:32:23,677 - INFO - Reconciliation Ends
2025-05-17 17:32:53,940 - INFO - Entered Main Function...
2025-05-17 17:32:54,030 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:32:54,030 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:32:54,031 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:32:54,031 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:32:54,032 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:32:54,032 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:33:01,324 - INFO - Entered Main Function...
2025-05-17 17:33:01,415 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:33:01,415 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:33:01,416 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:33:01,416 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:33:04,828 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:33:04,886 - INFO - Filteration Ends
2025-05-17 17:33:04,888 - INFO - Reconciliation Ends
2025-05-17 17:33:35,109 - INFO - Entered Main Function...
2025-05-17 17:33:35,243 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:33:35,243 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:33:35,244 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:33:35,244 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:33:35,244 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:33:35,245 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:33:43,042 - INFO - Entered Main Function...
2025-05-17 17:33:43,138 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:33:43,138 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:33:43,139 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:33:43,139 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:33:46,352 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:33:46,407 - INFO - Filteration Ends
2025-05-17 17:33:46,409 - INFO - Reconciliation Ends
2025-05-17 17:34:35,766 - INFO - Entered Main Function...
2025-05-17 17:34:35,854 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:34:35,854 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:34:35,855 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:34:35,855 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:34:35,856 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:34:35,856 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:34:43,348 - INFO - Entered Main Function...
2025-05-17 17:34:43,415 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:34:43,415 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:34:43,416 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:34:43,416 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:34:47,118 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:34:47,225 - INFO - Filteration Ends
2025-05-17 17:34:47,249 - INFO - Reconciliation Ends
2025-05-17 17:41:18,014 - INFO - Entered Main Function...
2025-05-17 17:41:18,291 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:41:18,292 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:41:18,294 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:41:18,295 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:41:18,301 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-17 17:41:18,301 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-17 17:41:19,193 - INFO - Report generated for Recharge
2025-05-17 17:41:28,843 - INFO - Entered Main Function...
2025-05-17 17:41:30,010 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 17:41:30,011 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 17:41:30,022 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 17:41:30,024 - INFO - Fetching data from HUB for Recharge
2025-05-17 17:41:34,201 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 17:41:34,822 - INFO - Filteration Ends
2025-05-17 17:41:35,027 - INFO - Reconciliation Ends
2025-05-17 17:41:40,104 - INFO - Report generated for Recharge
2025-05-17 18:04:35,400 - INFO - Entered Main Function...
2025-05-17 18:04:36,098 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:04:36,098 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:04:36,099 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:04:36,099 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:04:40,108 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:04:40,205 - INFO - Filteration Ends
2025-05-17 18:04:40,232 - INFO - Reconciliation Ends
2025-05-17 18:07:23,624 - INFO - Entered Main Function...
2025-05-17 18:07:24,268 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:07:24,269 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:07:24,270 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:07:24,270 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:07:28,293 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:07:28,346 - ERROR - Error in main(): cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid
2025-05-17 18:07:30,532 - INFO - Entered Main Function...
2025-05-17 18:07:30,705 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:07:30,705 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:07:30,710 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:07:30,710 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:07:34,521 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:07:34,577 - ERROR - Error in main(): cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid
2025-05-17 18:07:42,562 - INFO - Entered Main Function...
2025-05-17 18:07:42,638 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:07:42,638 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:07:42,639 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:07:42,640 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:07:46,611 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:07:46,694 - ERROR - Error in main(): cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid
2025-05-17 18:16:25,980 - INFO - Entered Main Function...
2025-05-17 18:16:26,859 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:16:26,859 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:16:26,859 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:16:26,859 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:16:30,833 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:16:30,923 - INFO - Filteration Ends
2025-05-17 18:16:30,941 - INFO - Reconciliation Ends
2025-05-17 18:16:57,738 - INFO - Entered Main Function...
2025-05-17 18:16:57,893 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:16:57,893 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:16:57,894 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:16:57,895 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:17:01,585 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-17 18:17:01,585 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:17:01,660 - INFO - Filteration Ends
2025-05-17 18:17:01,682 - INFO - Reconciliation Ends
2025-05-17 18:19:50,637 - INFO - Entered Main Function...
2025-05-17 18:19:50,979 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:19:50,980 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:19:50,980 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:19:50,980 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:19:55,026 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:19:55,069 - ERROR - Error in main(): ('Id', 'TranAmountTotal', 'VendorSubServiceMappingId')
2025-05-17 18:19:59,181 - INFO - Entered Main Function...
2025-05-17 18:19:59,246 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:19:59,246 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:19:59,246 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:19:59,246 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:20:02,940 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:20:03,002 - ERROR - Error in main(): ('Id', 'TranAmountTotal', 'VendorSubServiceMappingId')
2025-05-17 18:23:10,643 - INFO - Entered Main Function...
2025-05-17 18:23:10,994 - INFO - Records found within the date range. Running reconciliation...
2025-05-17 18:23:10,994 - INFO - Entering Reconciliation for Recharge Service
2025-05-17 18:23:10,995 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-17 18:23:10,995 - INFO - Fetching data from HUB for Recharge
2025-05-17 18:23:15,295 - INFO - Filteration Starts for Inward service Recharge
2025-05-17 18:23:15,352 - INFO - Filteration Ends
2025-05-17 18:23:15,366 - INFO - Reconciliation Ends
