2025-05-19 12:26:17,834 - INFO - Entered Main Function...
2025-05-19 12:26:18,496 - ERROR - Error in main(): 'DATE'
2025-05-19 12:26:18,605 - INFO - Report generated for Recharge
2025-05-19 12:26:53,482 - INFO - Entered Main Function...
2025-05-19 12:26:53,740 - WARNING - No records found within the given date range!
2025-05-19 12:28:15,920 - INFO - Entered Main Function...
2025-05-19 12:28:16,010 - WARNING - No records found within the given date range!
2025-05-19 12:32:49,528 - INFO - Entered Main Function...
2025-05-19 12:32:49,608 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:32:49,608 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:32:49,610 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:32:49,610 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:32:53,609 - INFO - Filteration Starts for  service Recharge
2025-05-19 12:32:53,820 - INFO - Filteration Ends
2025-05-19 12:32:53,874 - INFO - Reconciliation Ends
2025-05-19 12:33:07,299 - INFO - Entered Main Function...
2025-05-19 12:33:07,383 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:33:07,383 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:33:07,384 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:33:07,384 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:33:11,733 - INFO - Filteration Starts for  service Recharge
2025-05-19 12:33:11,888 - INFO - Filteration Ends
2025-05-19 12:33:11,919 - INFO - Reconciliation Ends
2025-05-19 12:36:35,795 - INFO - Entered Main Function...
2025-05-19 12:36:35,873 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:36:35,873 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:36:35,874 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:36:35,874 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:36:35,876 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-19 12:36:35,876 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-19 12:36:37,551 - INFO - Entered Main Function...
2025-05-19 12:36:37,627 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:36:37,628 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:36:37,628 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:36:37,629 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:36:47,752 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.1.3' (timed out)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-19 12:36:47,753 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-19 12:36:58,874 - INFO - Entered Main Function...
2025-05-19 12:36:58,941 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:36:58,942 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:36:58,942 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:36:58,942 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:37:08,942 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.1.3' (timed out)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-19 12:37:08,942 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-19 12:38:27,967 - INFO - Entered Main Function...
2025-05-19 12:38:28,710 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:38:28,710 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:38:28,711 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:38:28,711 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:38:32,041 - INFO - Filteration Starts for  service Recharge
2025-05-19 12:38:32,141 - INFO - Filteration Ends
2025-05-19 12:38:32,173 - INFO - Reconciliation Ends
2025-05-19 12:38:56,921 - INFO - Entered Main Function...
2025-05-19 12:38:57,006 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:38:57,007 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:38:57,008 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:38:57,008 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:39:00,814 - INFO - Filteration Starts for  service Recharge
2025-05-19 12:39:00,956 - INFO - Filteration Ends
2025-05-19 12:39:00,994 - INFO - Reconciliation Ends
2025-05-19 12:39:24,939 - INFO - Entered Main Function...
2025-05-19 12:39:25,008 - WARNING - No records found within the given date range!
2025-05-19 12:40:32,884 - INFO - Entered Main Function...
2025-05-19 12:40:32,974 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:40:32,975 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:40:32,976 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:40:32,976 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:40:32,978 - ERROR - Database error in recharge_Service(): Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
2025-05-19 12:40:32,978 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-19 12:42:39,716 - INFO - Entered Main Function...
2025-05-19 12:42:39,798 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:42:39,798 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:42:39,799 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:42:39,799 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:42:49,808 - ERROR - Database error in recharge_Service(): (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.1.3' (timed out)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-19 12:42:49,808 - ERROR - Error in main(): cannot access local variable 'result' where it is not associated with a value
2025-05-19 12:43:53,727 - INFO - Entered Main Function...
2025-05-19 12:43:53,813 - INFO - Records found within the date range. Running reconciliation...
2025-05-19 12:43:53,813 - INFO - Entering Reconciliation for Recharge Service
2025-05-19 12:43:53,813 - INFO - Recharge service: Column 'REFID' renamed to 'REFID'
2025-05-19 12:43:53,814 - INFO - Fetching data from HUB for Recharge
2025-05-19 12:43:56,987 - INFO - Filteration Starts for  service Recharge
2025-05-19 12:43:57,077 - INFO - Filteration Ends
2025-05-19 12:43:57,110 - INFO - Reconciliation Ends
